name: warp-clash-api Deployment

on:
  schedule:
    - cron: '0 0 * * 0'  # 每天周运行一次
  workflow_dispatch:  # 允许手动触发
  
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Clone
      run: |
        git clone https://github.com/vvbbnn00/WARP-Clash-API.git

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: peachz/warp-clash-api
        tags: |
          type=schedule,pattern={{date 'YYYYMMDD'}}
          type=raw,value=latest
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ./WARP-Clash-API
        file: ./WARP-Clash-API/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
