name: Sub-Store Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Get latest Sub-Store release
      id: get_latest_release
      run: |
        latest_release_url="https://api.github.com/repos/sub-store-org/Sub-Store/releases/latest"
        latest_version=$(curl -s $latest_release_url | grep -o '"tag_name": "\([^"]*\)"' | sed 's/"tag_name": "\(.*\)"/\1/')
        echo "Latest version: $latest_version"
        echo "sub_store_version=$latest_version" >> $GITHUB_OUTPUT

    - name: Download Sub-Store bundle
      run: |
        download_url="https://github.com/sub-store-org/Sub-Store/releases/download/${{ steps.get_latest_release.outputs.sub_store_version }}/sub-store.bundle.js"
        curl -L $download_url -o sub-store.bundle.js

    - name: Build Docker image
      run: |
        docker build -t sub-store:${{ steps.get_latest_release.outputs.sub_store_version }} .

        FROM node:16-alpine
        
        WORKDIR /app
        
        COPY . .
        
        RUN mkdir config
        
        EXPOSE 3000
        
        CMD cd config && node ../sub-store.bundle.js

    - name: Push to Docker Hub
      if: github.event_name == 'push'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push sub-store:${{ steps.get_latest_release.outputs.sub_store_version }}
