name: Sub-Store Deployment

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨运行一次
  workflow_dispatch:  # 允许手动触发
  
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Get latest Sub-Store release
      id: get_latest_release
      run: |
        latest_release_url="https://api.github.com/repos/sub-store-org/Sub-Store/releases/latest"
        latest_version=$(curl -s $latest_release_url | grep -o '"tag_name": "\([^"]*\)"' | sed 's/"tag_name": "\(.*\)"/\1/')
        echo "Latest version: $latest_version"
        echo "sub_store_version=$latest_version" >> $GITHUB_OUTPUT

    - name: Download Sub-Store bundle
      run: |
        download_url="https://github.com/sub-store-org/Sub-Store/releases/download/${{ steps.get_latest_release.outputs.sub_store_version }}/sub-store.bundle.js"
        curl -L $download_url -o sub-store.bundle.js

    - name: Build Dockerfile
      run: |
        cat << EOF > Dockerfile
        FROM node:16-alpine
        
        WORKDIR /app
        
        COPY . .
        
        RUN mkdir config
        
        EXPOSE 3000
        
        CMD cd config && node ../sub-store.bundle.js
        EOF

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: peachz/ssb
        flavor: latest=auto

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        # tags: peachz/ssb:${{ steps.get_latest_release.outputs.sub_store_version }}
